FROM php:8.0-fpm
WORKDIR /var/www
RUN apt-get update && apt-get install -y libzip-dev unzip && docker-php-ext-install pdo_mysql zip
RUN pecl install xdebug && docker-php-ext-enable xdebug
COPY . .
RUN chown -R www-data:www-data /var/www
CMD ["php-fpm"]
